name: workflow-for-java-project

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Get the project files.
      uses: actions/checkout@v4

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven_deps-${{ hashFiles('**/pom.xml') }}


    - name: Set up JDK 17.
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Add permissions to Maven
      run: chmod 755 ./mvnw

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests 

    - name: Test Application
      run: mvn test

    - name: List files in /target
      run: ls -l target/

  #  - name: Test JAR
  #    run: java -jar path/to/my-application.jar

        # mvn -B package --file pom.xml

